config/routes.rb
Rails.application.routes.draw do

  get 'sessions/destroy'

  resources :users

  get 'admin' => 'admin#index'
  controller :sessions do 
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :start 

  resources :vehicles
  resources :projects 
  resources :customers
  resources :prices
  resources :comments
  resources :logout
  resources :rentals
  resources :alerts

 root :to => 'start#index'

end

app/models/alert.rb
class Alert < ActiveRecord::Base
  belongs_to :customer
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  validates :name, :surname, presence: true
  validates :age, numericality: true, allow_blank: true
  has_many :alerts
end

app/models/rental.rb
class Rental < ActiveRecord::Base
  belongs_to :vehicle
end

app/models/start.rb
class Start < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  validates :brand, :model, presence: true
  validates :year,:power, numericality: true, allow_blank: false
  has_many :rentals
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end
end

app/controllers/alerts_controller.rb
class AlertsController < ApplicationController
  def new
    @customer =Customer.find(params[:id])
    @alert=@customer.alerts.build
  end

  def create
    @customer = Customer.find(params[:id])
    @alert=@customer.alerts.build(params.require(:alert).permit(:description))

    if @alert.save
      redirect_to new_alert_path(:id=>@customer.id)
    end
  end



  private
    def alert_params
      params.require(:alert).permit (:description )
    end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:name, :surname, :age)
    end
end

app/controllers/prices_controller.rb
class PricesController < ApplicationController
  def index
  end
end

app/controllers/start_controller.rb
class StartController < ApplicationController
  def index
  end
  
  def new
  	redirect_to 'users#new'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :authorize, only: [:new, :create, :index]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_path, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new'}
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_url, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/alerts_helper.rb
module AlertsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/helpers/rentals_helper.rb
module RentalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/start_helper.rb
module StartHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/customers/_form.html.erb
<%= simple_form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited
      this article from being saved:</h2>
    <ul>
      <% @customer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    </div>
  <% end %>



  <div class="form-inputs">
  	<div class="field">
	  	<%= f.label :name %></br>
	    <%= f.text_field :name  %>
  	</div>
  	<div class="field">
	  	<%= f.label :surname %></br>
	    <%= f.text_field :surname  %>
    </div>
  	<div class="field">
      <%= f.input :age, :input_html => { :wrap => :soft, :rows => 2}, :label => 'Age: ', :label_html => { :class => 'type' } %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<section id="content">
  <div class="sub-page">
    <div class="sub-page-left">
      <h2>Editing Customer</h2>
      <%= render 'form' %>
      <p class="button"><%= link_to 'Back', customers_path %></p>
      <p class="button"><%= link_to 'Delete', customer_path, method: :delete, data: { confirm: 'Are you sure?' } %></p>
    </div>
    <div class="sub-page-right">
      <%= render 'shared/openh' %>
    </div>
  </div>
</section>

app/views/customers/index.html.erb
<section id="content">
  <div class="sub-page">
    <div class="sub-page-left">
      <p id="notice"><%= notice %></p>
      <h2 class="p4">Customers</h2><hr/>

      <table>
        <thead>
          <tr>
            <th>#</th>
            <th>Name</th>
            <th>Surname</th>
            <th>Age</th>
            <th>Action</th>
          </tr>
        </thead>

        <tbody>
          <% @i=0 %>
          <% @customers.each do |customer| %>
            <%@i=@i+1%>
            <tr>
              <td><%=@i%></td>
              <td><%= customer.name %></td>
              <td><%= customer.surname %></td>
              <td><%= customer.age %></td>
              <td><%= link_to 'Show', customer %></td>
            </tr>
          <% end %>
        </tbody>
      </table><br/>
      <% if current_user.name == 'admin' %>
        <div class="button"><%= link_to 'New Customer', new_customer_path %></div>
      <%end%>
    </div>
    <div class="sub-page-right">
      <%= render 'shared/openh' %>
    </div>
  </div>
</section> 

app/views/customers/new.html.erb
<section id="content">
  <div class="sub-page">
    <div class="sub-page-left">

      <h2>New Customer</h2>
      <hr/>

      <%= render 'form' %>

      <div class="button"><%= link_to 'Back', customers_path %></div>
    </div>
    <div class="sub-page-right">
      <%= render 'shared/openh' %>
    </div>


  </div>
</section>

app/views/customers/show.html.erb
<section id="content">
  <div class="sub-page">
    <div class="sub-page-left">
      <h2 class="p4">Details</h2>
      <p id="notice"><%= notice %></p>
      <p>
        <strong>Name:</strong>
        <%= @customer.name %>
      </p>
      <p>
        <strong>Surname:</strong>
        <%= @customer.surname %>
      </p>
      <p>
        <strong>Age:</strong>
        <%= @customer.age %>
      </p>

      <% if current_user.name == 'admin' %>
        <p class="button"><%= link_to 'Warnings', :controller=>:alerts, :action =>:new, :id=>@customer.id %></p>
        <p class="button"><%= link_to 'Edit', edit_customer_path %></p>
        <p class="button"><%= link_to 'Back', customers_path %></p>
      <%end%>
    </div>
    <div class="sub-page-right">
      <%= render 'shared/openh' %>
    </div>
  </div>
</section>